home: /root/.bbot
modules:
   nmap:
     top_ports: 100
     ports: '22,80,443,500,4500'
#     timing: T4
#     skip_host_discovery: true
   json:
#     output_file: 'output.json'
     console: false
     siem_friendly: false
output_modules:
   neo4j:
     uri: bolt://graph.internal:7687
